package com.serviceId;
// Generated 4 Jun, 2014 11:33:29 AM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

/**
 * Customer generated by hbm2java
 */
//@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = As.PROPERTY, property = "@class")
@Entity
@Table(name="customer"
)
public class Customer implements java.io.Serializable {


     private Long pId;
     private String email;
     private String first_name;
     private String last_name;
     private Set<Orders> orderses = new HashSet<Orders>(0);
     private Set<Address> addresses = new HashSet<Address>(0);

    public Customer() {
    }

    public Customer(String email, String firstname, String lastname, Set<Orders> orderses, Set<Address> addresses) {
       this.email = email;
       this.first_name = firstname;
       this.last_name = lastname;
       this.orderses = orderses;
       this.addresses = addresses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getPId() {
        return this.pId;
    }
    
    public void setPId(Long id) {
        this.pId = id;
    }

    
    @Column(name="email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="firstname")
    public String getFirst_name() {
        return this.first_name;
    }
    
    public void setFirst_name(String firstname) {
        this.first_name = firstname;
    }

    
    @Column(name="lastname")
    public String getLast_name() {
        return this.last_name;
    }
    
    public void setLast_name(String lastname) {
        this.last_name = lastname;
    }
@JsonIgnore
@OneToMany(fetch=FetchType.EAGER, mappedBy="customer")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

    @JsonIgnore
    @OneToMany(fetch=FetchType.EAGER)
    @JoinColumn(name="email", nullable=false)
    public Set<Address> getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set<Address> addresses) {
        this.addresses = addresses;
    }

	@Override
	public String toString() {
		return "Customer [id=" + pId + ", email=" + email + ", firstname="
				+ first_name + ", lastname=" + last_name + ", orderses="
				+ orderses + ", addresses=" + addresses + "]";
	}




}


