package com.serviceId;
// Generated 4 Jun, 2014 11:33:29 AM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

/**
 * Lineitem generated by hbm2java
 */
//@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = As.PROPERTY, property = "@class")
@Entity
@Table(name="lineitem"
)
public class Lineitem implements java.io.Serializable {


     private Long id;
     private Orders orders;
     private Product product;
     private int amount;
     private BigDecimal price;

    public Lineitem() {
    }

	
    public Lineitem(int amount, BigDecimal price) {
        this.amount = amount;
        this.price = price;
    }
    public Lineitem(Orders orders, Product product, int amount, BigDecimal price) {
       this.orders = orders;
       this.product = product;
       this.amount = amount;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="order_id")
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="product_id")
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="amount", nullable=false)
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }

    
    @Column(name="price", nullable=false)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }


	@Override
	public String toString() {
		return "Lineitem [id=" + id + ", orders=" + orders + ", product="
				+ product + ", amount=" + amount + ", price=" + price + "]";
	}




}


