package com.serviceId;
// Generated 4 Jun, 2014 11:33:29 AM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;

/**
 * Product generated by hbm2java
 */
//@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = As.PROPERTY, property = "@class")
@Entity
@Table(name="product"
)
public class Product implements java.io.Serializable {


     private Long id;
     private String description;
     private String name;
     private BigDecimal price;
     private Set<Lineitem> lineitems = new HashSet<Lineitem>(0);

    public Product() {
    }

	
    public Product(String name, BigDecimal price) {
        this.name = name;
        this.price = price;
    }
    public Product(String description, String name, BigDecimal price, Set<Lineitem> lineitems) {
       this.description = description;
       this.name = name;
       this.price = price;
       this.lineitems = lineitems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="price", nullable=false)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @JsonIgnore
@OneToMany(fetch=FetchType.EAGER, mappedBy="product")
    public Set<Lineitem> getLineitems() {
        return this.lineitems;
    }
    
    public void setLineitems(Set<Lineitem> lineitems) {
        this.lineitems = lineitems;
    }


	@Override
	public String toString() {
		return "Product [id=" + id + ", description=" + description + ", name="
				+ name + ", price=" + price + ", lineitems=" + lineitems + "]";
	}




}


